# Generated by Django 4.2.dev20221108194129 on 2024-03-14 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp3", "0002_add_publication_date_to_book"),
    ]

    operations = []
