# Generated by Django 4.2.dev20221108194129 on 2024-04-13 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("myapp3", "0008_taskassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assigned_to2",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_tasks", to="myapp3.employee"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("done", "Done"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
