# Generated by Django 4.2.dev20221108194129 on 2024-04-13 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp3", "0009_task_assigned_to2_task_end_date_task_start_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assigned_to2",
        ),
    ]
