# Generated by Django 4.2.dev20221108194129 on 2024-04-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp3", "0011_remove_task_assigned_to_task_assigned_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
            ],
        ),
    ]
