# Generated by Django 4.2.dev20221108194129 on 2024-04-20 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp3", "0013_remove_taskassignment_progress_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaskAssignment",
        ),
    ]
