# Generated by Django 4.2.dev20221108194129 on 2024-04-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp3", "0014_delete_taskassignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="myapp3.basic_employee_information"
            ),
        ),
    ]
