# Generated by Django 4.2.dev20221108194129 on 2024-04-21 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp3", "0017_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
