# Generated by Django 4.2.dev20221108194129 on 2024-04-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp3", "0019_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="announcements",
                        to="myapp3.basic_employee_information",
                    ),
                ),
            ],
        ),
    ]
